Server:
  Folder: "{path/to/server/folder}"
  FileName: "{server.jar}"
  Protocol: 756
  Version: "1.17.1"
Commands:
  StartServer: "java <Commands.StartServerParam> -jar <Server.FileName> nogui"
  StartServerParam: "-Xmx1024M -Xms1024M"
  StopServer: "stop"
  StopServerAllowKill: 10
Msh:
  Debug: 1 # [0 - 4]
  InfoHibernation: "                   §fserver status:\n                   §b§lHIBERNATING"
  InfoStarting: "                   §fserver status:\n                    §6§lWARMING UP"
  NotifyUpdate: true
  Port: "25555"
  TimeBeforeStoppingEmptyServer: 30
